[tool.isort]
multi_line_output = 3
recursive = true
include_trailing_comma = true
line_length = 88
known_common = 'cct_common'
known_first_party = 'tests'
combine_as_imports = true
sections='FUTURE,STDLIB,THIRDPARTY,COMMON,FIRSTPARTY,LOCALFOLDER'

[tool.black]
include = '\.py$'
skip-string-normalization = true
target-version = ['py36']