 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.3
     steps:
       - checkout
       - run: pip install -r requirements.txt
       - run: pip install -r dev_requirements.txt
       - run: make test
